# Generated by Django 4.1.2 on 2022-11-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecHistory',
            fields=[
                ('rh_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('symtominput', models.CharField(blank=True, max_length=4000, null=True)),
                ('rec_dpt', models.CharField(blank=True, max_length=100, null=True)),
                ('input_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rec_history',
                'managed': False,
            },
        ),
    ]
