# Generated by Django 4.1.2 on 2022-11-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_alter_rechistory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('rh_key', models.BigAutoField(primary_key=True, serialize=False)),
                ('symptominput', models.CharField(blank=True, max_length=4000, null=True)),
                ('rec_dpt', models.CharField(blank=True, max_length=100, null=True)),
                ('input_date', models.CharField(blank=True, max_length=100, null=True)),
                ('select_symptom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_history',
                'managed': False,
            },
        ),
    ]
