# Generated by Django 4.1.2 on 2022-11-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_rechistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rechistory',
            table=None,
        ),
    ]
